### ISSUE TITLE
Package cannot be loaded on case-insensitive file systems

### ISSUE THREAD

**Issue by iamed2** [ExpandingMan/Anamnesis.jl#1]
`include("anamnesis.jl")` will actually load `"Anamnesis.jl"` and break compilation. Renaming `anamnesis.jl` would fix it.

**Comment by ExpandingMan** [comment]
Done!

FYI, to be honest this package has been semi-abandoned, but I still have a ton of potential use for it so I'm considering doing a thorough overhaul.  See #2 for a partial list of things I'd like to do.  If it's something I decide to do, I'll probably start within the next couple of weeks.

**Comment by iamed2** [comment]
Thanks!

TBH I was just using it for call-site memoization and didn't touch the file system stuff.
